// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuoC_7_corZKzG2Y8y0O2PfXxV6MvJx5A',
    appId: '1:626463636097:web:0aa5efdd7ea0bae7c26b80',
    messagingSenderId: '626463636097',
    projectId: 'ulak-531f6',
    authDomain: 'ulak-531f6.firebaseapp.com',
    storageBucket: 'ulak-531f6.appspot.com',
    measurementId: 'G-MNJ8TLMJ14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIEytHoPl7xh4SvYXtEC6aHcbYj1Q8yj8',
    appId: '1:626463636097:android:436c93b440b67a6bc26b80',
    messagingSenderId: '626463636097',
    projectId: 'ulak-531f6',
    storageBucket: 'ulak-531f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtmuMvHNOLxa1NKCvTmSQM3f10jCzh2EA',
    appId: '1:626463636097:ios:5cf2002079f3acdbc26b80',
    messagingSenderId: '626463636097',
    projectId: 'ulak-531f6',
    storageBucket: 'ulak-531f6.appspot.com',
    iosBundleId: 'com.example.ulak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtmuMvHNOLxa1NKCvTmSQM3f10jCzh2EA',
    appId: '1:626463636097:ios:591238343115c1b9c26b80',
    messagingSenderId: '626463636097',
    projectId: 'ulak-531f6',
    storageBucket: 'ulak-531f6.appspot.com',
    iosBundleId: 'com.example.ulak.RunnerTests',
  );
}
